### ISSUE TITLE
workbook.active_fields method throws IndexError: list index out of range

### ISSUE THREAD

**Issue by p2c4** [bpewyllie/TableauDesktopPy#2]

**Comment by p2c4** [comment]
[Chapter 1 - Sample twbx Workbook.zip](https://github.com/bpewyllie/TableauDesktopPy/files/13910476/Chapter.1.-.Sample.twbx.Workbook.zip)

`import TableauDesktopPy as tdp`
`my_workbook = tdp.Workbook("C:\\Users\\user\\Documents\\SampleWorkbooks\\Chapter 1 - First Workbook.twbx")`
`print(my_workbook.active_fields)`

Error
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\TableauDesktopPy\TableauDesktopPy.py", line 37, in active_fields
    return self._get_active_fields()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\TableauDesktopPy\TableauDesktopPy.py", line 242, in _get_active_fields
    ds_caption = self.xml.xpath(
IndexError: list index out of range
